services:
  collect-api:
    image: ghcr.io/dfe-digital/schoolaccount-collectapi:latest
    platform: linux/amd64
    container_name: collect-api
    build:
      context: .
      dockerfile: src/SchoolAccount.Collect.Api/Dockerfile
    ports:
      - "5101:8080"

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"
