<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchoolAccount.Collect.Application\SchoolAccount.Collect.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SchoolAccount.Collect.ArchitectureTests" />
  </ItemGroup>
</Project>
