@API_HostAddress = http://localhost:5101

### Get status for school with Local Authority
POST {{API_HostAddress}}/status
Accept: application/json
Content-Type: application/json

{
  "id": "user-1",
  "email": "test.user@email.com",
  "organisations": [
    {
      "id": "2E774B32-E4DB-445B-B915-736C777FF5A4",
      "name": "East Herrington Primary Academy",
      "category": {
        "id": "001",
        "name": "Establishment"
      },
      "ukprn": "10037611",
      "establishmentNumber": "2091",
      "localAuthority": {
        "id": "502EF2E9-2CA6-4905-9BF7-E80695BD5717",
        "name": "SUNDERLAND CITY METROPOLITAN BOROUGH COUNCIL",
        "code": "394"
      }
    }
  ]
}

### Get status for trust school
POST {{API_HostAddress}}/status
Accept: application/json
Content-Type: application/json

{
  "id": "user-1",
  "email": "test.user@email.com",
  "organisations": [
    {
      "id": "DD9F7BD6-2828-4FE7-B6DA-7C7C028ED479",
      "name": "BALMORAL LEARNING TRUST",
      "category": {
        "id": "010",
        "name": "Multi-Academy Trust"
      },
      "ukprn": "10059806"
    }
  ] 
}

### Validation error for GetStatus with empty body
POST {{API_HostAddress}}/status
Accept: application/json
Content-Type: application/json

{}

### Validation error for GetStatus with empty trust school fields
POST {{API_HostAddress}}/status
Accept: application/json
Content-Type: application/json

{
  "id": "",
  "name": "",
  "organisations": [
    {
      "id": "",
      "name": "",
      "category": {
        "id": "",
        "name": ""
      },
      "ukprn": ""
    }
  ]
}

### Validation errors for GetStatus with empty academy fields
POST {{API_HostAddress}}/status
Accept: application/json
Content-Type: application/json

{
  "id": "",
  "name": "",
  "organisations": [
    {
      "id": "",
      "name": "",
      "category": {
        "id": "",
        "name": ""
      },
      "ukprn": "",
      "establishmentNumber": "",
      "localAuthority": {
        "id": "",
        "name": "",
        "code": ""
      }
    }
  ]
}