@API_HostAddress = http://localhost:5101

### Get autumn school census action details
POST {{API_HostAddress}}/census/autumn-school-census
Accept: application/json
Content-Type: application/json

{
  "id": "user-1",
  "email": "test.user@email.com",
  "organisations": [
    {
      "id": "2E774B32-E4DB-445B-B915-736C777FF5A4",
      "name": "East Herrington Primary Academy",
      "category": {
        "id": "001",
        "name": "Establishment"
      },
      "ukprn": "10037611",
      "establishmentNumber": "2091",
      "localAuthority": {
        "id": "502EF2E9-2CA6-4905-9BF7-E80695BD5717",
        "name": "SUNDERLAND CITY METROPOLITAN BOROUGH COUNCIL",
        "code": "394"
      }
    }
  ]
}